spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/dev
    username: hello
    password: local
    platform: postgres

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug

